version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "teste@12345"
      ACCEPT_EULA: "Y"
    networks:
      - fastcommerce
    volumes:
      - sqlserver-data:/var/opt/mssql

  api.ocelot:
    build:
      context: .
      dockerfile: Api.Ocelot/Dockerfile
    container_name: api-ocelot
    ports:
      - "5000:5000"    
    networks:
      - fastcommerce
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5000
    volumes:
       - ./Api.Ocelot/ocelot.json:/app/ocelot.json

  api.catalog:
    build:
      context: .
      dockerfile: Api.Catalog/Dockerfile
    container_name: api-catalog
    ports:
      - "5001:5001"
    networks:
      - fastcommerce
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5001
    volumes:
       - ./Api.Catalog/CreateDatabase.sql:/app/CreateDatabase.sql

  api.checkout:
    build:
      context: .
      dockerfile: Api.Checkout/Dockerfile
    container_name: api-checkout
    ports:
      - "5002:5002"
    networks:
      - fastcommerce
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5002
  
  api.shipping:
    build:
      context: .
      dockerfile: Api.Shipping/Dockerfile
    container_name: api-shipping
    ports:
      - "5003:5003"
    networks:
      - fastcommerce
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5003

  api.customer:
    build:
      context: .
      dockerfile: Api.Customer/Dockerfile
    container_name: api-customer
    ports:
      - "5004:5004"
    networks:
      - fastcommerce
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5004

  ui.server:
    build:
      context: .
      dockerfile: UI/UI/Dockerfile
    container_name: ui-server
    ports:
      - "5005:5005"
    networks:
      - fastcommerce
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5005

networks:
  fastcommerce:

volumes:
  sqlserver-data:
      